### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by wizicer**
Hello Chia team,

We are **Chiabee** from China, we are working on the Chinese translation of this wonderful project. This PR is not ready to be merged right now but intended to be a signal letting you or others know we are trying hard to make it available.

What we achieved:
1. Full translation of every doc page by our staff manually instead of machine translation.
2. Translated home page strictly followed docusaurus i18n specification.
3. Deployed to https://chiadocs.chiabee.net/

What is missing(also a plan):
1. Individual PR for i18n-ready home page with default English. (Other translations could also benefit from this change)
2. Individual PR for translated Chinese resources(doc + message).

As I haven't seen any contribution guidance, I'm not sure if I'm doing right, any suggestion is appreciated.

Also, if possible, share with us how other translations are planned to deploy.

### CODE REVIEW

**Comment by mariano54** [comment]
really looking forward to having a Chinese translation! Thank you for contributing. I am not sure the best way to do it, @danieljperry can you support?

**Comment by danieljperry** [comment]
Thanks, guys! I'll take a look.

**Comment by JelloHuang** [comment]
pls setup new dir

**Comment by danieljperry** [comment]
Hi @wizicer, we are actively working on getting this merged, but will need a bit more time. Thanks for setting this up!

**Comment by wizicer** [comment]
> pls setup new dir

@JelloHuang Thanks for your comments. Can you elaborate on this?

We mostly set up the translation file under `i18n/cn` directory according to the Docusaurus i18n tutorial.  Some translations require changes in the root as #18 mentioned. That's why we want #18 to get merged first, and the English site should not be affected by it.

We want our later changes limited to `i18n/cn` directory only.

**Comment by JelloHuang** [comment]
> > pls setup new dir
> 
> @JelloHuang Thanks for your comments. Can you elaborate on this?
> 
> We mostly set up the translation file under `i18n/cn` directory according to the Docusaurus i18n tutorial. Some translations require changes in the root as #18 mentioned. That's why we want #18 to get merged first, and the English site should not be affected by it.
> 
> We want our later changes limited to `i18n/cn` directory only.

it mean that we setup new dir like https://github.com/Chia-Network/chia-docs/pull/35
then push all chinese doc to the location

**Comment by wizicer** [comment]
> > > pls setup new dir
> > 
> > 
> > @JelloHuang Thanks for your comments. Can you elaborate on this?
> > We mostly set up the translation file under `i18n/cn` directory according to the Docusaurus i18n tutorial. Some translations require changes in the root as #18 mentioned. That's why we want #18 to get merged first, and the English site should not be affected by it.
> > We want our later changes limited to `i18n/cn` directory only.
> 
> it mean that we setup new dir like #35 then push all chinese doc to the location

Should we upload all the built files into this folder?
(Why I have the question is because it seems weird to me as Docusaurus already provided a translation mechanism, why not utilize that?)

**Comment by JelloHuang** [comment]
> 
I am not familiar with web design.So if is more convince  with docusaurus/jekyllrb for doc and web style  ,let`s make it.~_~ thx

**Comment by JelloHuang** [comment]
one problem is that  there is lack of website of the doc

**Comment by wizicer** [comment]
> one problem is that there is lack of website of the doc

I'm not sure what lacks you mean?

**Comment by JelloHuang** [comment]
> > one problem is that there is lack of website of the doc
> 
> I'm not sure what lacks you mean?

no site for github.com/Chia-Network/chia-docs/

**Comment by wizicer** [comment]
> > > one problem is that there is lack of website of the doc
> > 
> > 
> > I'm not sure what lacks you mean?
> 
> no site for github.com/Chia-Network/chia-docs/



> > > one problem is that there is lack of website of the doc
> > 
> > 
> > I'm not sure what lacks you mean?
> 
> no site for github.com/Chia-Network/chia-docs/

- https://docs.chia.net/ for English version
- https://chiadocs.chiabee.net/ for Chinese version

What extra are you expected?

**Comment by JelloHuang** [comment]
> > > > one problem is that there is lack of website of the doc
> > > 
> > > 
> > > I'm not sure what lacks you mean?
> > 
> > 
> > no site for github.com/Chia-Network/chia-docs/
> 
> > > > one problem is that there is lack of website of the doc
> > > 
> > > 
> > > I'm not sure what lacks you mean?
> > 
> > 
> > no site for github.com/Chia-Network/chia-docs/
> 
> * https://docs.chia.net/ for English version
> * https://chiadocs.chiabee.net/ for Chinese version
> 
> What extra are you expected?

okay u have found the site.

**Comment by wizicer** [comment]
If any extra suggestions or contribution guides are available, don't hesitate to let me know. Thanks.

**Comment by wizicer** [comment]
@roybotbot  I created `icerdesign` on crowdin.com. Please take me in. I will evaluate the workload first and then may invite my team member to help later.

**Comment by wizicer** [comment]
> > @roybotbot I created `icerdesign` on crowdin.com. Please take me in. I will evaluate the workload first and then may invite my team member to help later.
> 
> I can't invite directly. Please follow this link: https://crwd.in/chia-docs @wizicer

I joined, nothing I can work on now, let me know if it is ready.

**Comment by wizicer** [comment]
> @wizicer it should be all set up now.

Thanks. Got see. However, I still have following questions:
1. How does the homepage get translated?
2. How does the Chinese version get published?
3. Where does the `Edit this page` link to (especially in the Chinese version)?
4. Can the reference source text show together with the translation(or in some other type of form)?

PS: It seems crowdin does not allow us to import what we already have (translated markdowns). Typing translation sentence by sentence makes me like an office clerk instead of a developer(especially always work with vi key binding).

**Comment by Rigidity** [comment]
Closing due to inactivity. We are using Crowdin for translations.

**Pull request closed without merging**
