### PR TITLE
Update full-node.md to reflect latest documentation formatting

### PR DESCRIPTION
**Pull request by KryptomineCH**
- corrections on healtz & get_routes (invalid boolean)
- fixed invalid json for get_all_mempool_items (was cut off early)

### CODE REVIEW

**Comment by KryptomineCH** [comment]
related to:
https://github.com/Chia-Network/chia-docs/issues/262

**Comment by KryptomineCH** [comment]
please review this. 
I put a lot of effort into it.

**Comment by danieljperry** [comment]
Thanks for this. I'll merge your changes after the checks pass. Also just to let you know, I have been working on a rewrite of this doc, as well as a refresh of the other RPC docs, which should be coming soon.

**Comment by KryptomineCH** [comment]
checks wont pass due to denied permission (403 error on docker)
```
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/chia-network/chia-docs:sha-47d479fb6b34c36a018b9cfa4bb12e3849087908: unexpected status: 403 Forbidden
```

**Comment by danieljperry** [comment]
Sorry, the checks are still failing with a permissions issue. Our IPS team is working on fixing this. Meanwhile, I have made a large number of updates to our RPC docs, with many more examples than before.

**Comment by KryptomineCH** [comment]
I think the pull request can be closed since the update

**Pull request closed without merging**
