### PR TITLE
Update tx block time and observer keys

### PR DESCRIPTION
**Pull request by danieljperry**
-- Transaction block time had been calculated incorrectly. Updated to fix.
-- HD keys should be referred to as observer keys in this context.

### CODE REVIEW

**Comment by mariano54** [comment]
It is actually slightly more than 3.5, the formula is:
`(1/(e^(0.5)-1)+4)*9.375`

**Comment by hoffmang9** [comment]
I think you need to put into English why it's that formula @mariano54

**Review by hoffmang9 — APPROVED** [review]
lgtm now

**Comment by danieljperry** [comment]
I updated foliage.md to remove mentions of the old formula.

**Review by hoffmang9 — APPROVED** [review]
now AOK

**Review by hoffmang9 — APPROVED** [review]
lgtm

**Pull request merged**
