### PR TITLE
Update nfts.md - cli:`wallet nft list` args `--num`, `--start-index` - ETA 2.1.0

### PR DESCRIPTION
**Pull request by yyolk**
Include the additional `--num`, `--start-index` options for `chia wallet nft list ...` for PR https://github.com/Chia-Network/chia-blockchain/pull/15342

[**Estimated to be in 2.1.0 release**](https://github.com/Chia-Network/chia-docs/pull/303#issuecomment-1732118212)

### CODE REVIEW

**Comment by yyolk** [comment]
updated description for `--start-index` to align with PR review: https://github.com/Chia-Network/chia-blockchain/pull/15342#discussion_r1230637759

**Comment by yyolk** [comment]
Don't believe I can request a review through the PR, no option to select anyone afaict.
So this comment will serve as one!

This PR could be merged now with Chia-Network/chia-blockchain#15342 getting merged.

**Comment by yyolk** [comment]
Originally appeared to be in the 2.0.1 release with commit in [2.0.1-b2](https://github.com/Chia-Network/chia-blockchain/releases/tag/2.0.1-b2), but 2.0.1 didn't include it.

It does appear to be in the planned 2.1.0 release, from [2.1.0-rc2](https://github.com/Chia-Network/chia-blockchain/releases/tag/2.1.0-rc2):

```
$ chia version && chia wallet nft list -h
2.1.0rc2
Usage: chia wallet nft list [OPTIONS]

  List the current NFTs

Options:
  -wp, --wallet-rpc-port INTEGER  Set the port where the Wallet is hosting the
                                  RPC interface. See the rpc_port under wallet
                                  in config.yaml
  -f, --fingerprint INTEGER       Fingerprint of the wallet to use
  -i, --id INTEGER                Id of the NFT wallet to use  [required]
  --num INTEGER                   Number of NFTs to return
  --start-index INTEGER           Which starting index to start listing NFTs
                                  from
  -h, --help                      Show this message and exit.
```

I'm sorta familiar with other patches usually coming in two later, so in the future I'll suggest to merge any updates to docs to reflect updates to [chia-blockchain](https://github.com/Chia-Network/chia-blockchain) in a stable release, which the docs reflect.

**Comment by yyolk** [comment]
This is ready to be merged with https://github.com/Chia-Network/chia-blockchain/releases/tag/2.1.0 now released

I'm unable to assign reviewers because of my permissions, so pinging @danieljperry to take a look when they can.

**Review by hoffmang9 — APPROVED** [review]

**Pull request merged**
